
CREATE TABLE saikyo_new.statements
(
    `_id` FixedString(30),
    `hash` FixedString(50),
    `statement` String,
    `timestamp` DateTime64(3),
    `created_at` DateTime64(3) DEFAULT now()
)
ENGINE = ReplacingMergeTree
ORDER BY (timestamp, _id)
SETTINGS index_granularity = 16384


CREATE TABLE saikyo_new.statements_target
(
    `_id` FixedString(30),
    `hash` FixedString(50),
    `statement_id` FixedString(50),
    `version` LowCardinality(String),
    `platform` LowCardinality(String),
    `actor_name_id` LowCardinality(String),
    `actor_name_role` LowCardinality(String),
    `actor_objectType` LowCardinality(String),
    `actor_account_name` LowCardinality(String),
    `actor_account_homePage` String,
    `verb_id` LowCardinality(String),
    `verb_display_en` String,
    `object_objectType` LowCardinality(String),
    `object_id` FixedString(255),
    `object_definition_name_en` String,
    `object_definition_description_en` String,
    `operation_name` String,
    `description` String,
    `marker_color` String,
    `marker_position` String,
    `marker_text` String,
    `memo_text` String,
    `memo_hand` String,
    `memo_hand_bg` String,
    `process_code` String,
    `log_id` String,
    `contents_id` String,
    `contents_name` String,
    `page_no` FixedString(50),
    `object_version` String,
    `device_code` LowCardinality(String),
    `competency1` String,
    `competency2` String,
    `competency3` String,
    `uniqId` String,
    `parentid` String,
    `canvas` String,
    `lineColor` String,
    `context_id` String,
    `context_title` String,
    `context_label` String,
    `school_id` FixedString(50),
    `authority_objectType` LowCardinality(String),
    `authority_name` String,
    `authority_mbox` String,
    `timestamp_raw` String,
    `timestamp` DateTime64(3),
    `stored` DateTime64(3),
    `is_parsed` UInt8
)
ENGINE = ReplacingMergeTree
ORDER BY (timestamp, _id)
SETTINGS index_granularity = 16384


CREATE MATERIALIZED VIEW saikyo_new.statements_mv TO saikyo_new.statements_target
(
    `_id` FixedString(30),
    `hash` FixedString(50),
    `statement_id` String,
    `version` String,
    `platform` String,
    `actor_name_id` String,
    `actor_name_role` String,
    `actor_objectType` String,
    `actor_account_name` String,
    `actor_account_homePage` String,
    `verb_id` String,
    `verb_display_en` String,
    `object_objectType` String,
    `object_id` String,
    `object_definition_name_en` String,
    `object_definition_description_en` String,
    `operation_name` String,
    `description` String,
    `marker_color` String,
    `marker_position` String,
    `marker_text` String,
    `memo_text` String,
    `memo_hand` String,
    `memo_hand_bg` String,
    `process_code` String,
    `log_id` String,
    `contents_id` String,
    `contents_name` String,
    `page_no` String,
    `object_version` String,
    `device_code` String,
    `competency1` String,
    `competency2` String,
    `competency3` String,
    `uniqId` String,
    `parentid` String,
    `canvas` String,
    `lineColor` String,
    `context_id` String,
    `context_title` String,
    `context_label` String,
    `school_id` String,
    `authority_objectType` String,
    `authority_name` String,
    `authority_mbox` String,
    `timestamp_raw` String,
    `timestamp` DateTime64(3),
    `stored` DateTime64(3),
    `is_parsed` UInt8
)
AS SELECT
    _id AS _id,
    hash AS hash,
    JSON_VALUE(statement, '$.id') AS statement_id,
    JSON_VALUE(statement, '$.version') AS version,
    JSON_VALUE(statement, '$.context.platform') AS platform,
    JSON_VALUE(statement, '$.actor.name_id') AS actor_name_id,
    JSON_VALUE(statement, '$.actor.name_role') AS actor_name_role,
    JSON_VALUE(statement, '$.actor.objectType') AS actor_objectType,
    JSON_VALUE(statement, '$.actor.account.name') AS actor_account_name,
    JSON_VALUE(statement, '$.actor.account.homePage') AS actor_account_homePage,
    JSON_VALUE(statement, '$.verb.id') AS verb_id,
    JSON_VALUE(statement, '$.verb.display.en') AS verb_display_en,
    JSON_VALUE(statement, '$.object.objectType') AS object_objectType,
    JSON_VALUE(statement, '$.object.id') AS object_id,
    JSON_VALUE(statement, '$.object.definition.name.en') AS object_definition_name_en,
    JSON_VALUE(statement, '$.object.definition.description.en') AS object_definition_description_en,
    visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'operation_name') AS operation_name,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'description'), '') AS description,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'marker_color'), '') AS marker_color,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'marker_position'), '') AS marker_position,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'marker_text'), '') AS marker_text,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'memo_text'), '') AS memo_text,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'memo_hand'), '') AS memo_hand,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'memo_hand_bg'), '') AS memo_hand_bg,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'process_code'), '') AS process_code,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'log_id'), '') AS log_id,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'contents_id'), '') AS contents_id,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'contents_name'), '') AS contents_name,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'page_no'), '') AS page_no,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'version'), '') AS object_version,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'device_code'), '') AS device_code,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'competency1'), '') AS competency1,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'competency2'), '') AS competency2,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'competency3'), '') AS competency3,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'uniqId'), '') AS uniqId,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'parentid'), '') AS parentid,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'canvas'), '') AS canvas,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.object.definition.extensions'), 'lineColor'), '') AS lineColor,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.context.extensions'), 'context_id'), '') AS context_id,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.context.extensions'), 'context_title'), '') AS context_title,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.context.extensions'), 'context_label'), '') AS context_label,
    ifNull(visitParamExtractString(JSON_QUERY(statement, '$.context.extensions'), 'school_id'), '') AS school_id,
    JSON_VALUE(statement, '$.authority.objectType') AS authority_objectType,
    JSON_VALUE(statement, '$.authority.name') AS authority_name,
    JSON_VALUE(statement, '$.authority.mbox') AS authority_mbox,
    JSON_VALUE(statement, '$.timestamp') AS timestamp_raw,
    coalesce(parseDateTime64BestEffort(JSON_VALUE(statement, '$.timestamp'), 3), toDateTime64('1970-01-01 00:00:00.000', 3)) AS timestamp,
    coalesce(parseDateTime64BestEffort(JSON_VALUE(statement, '$.stored'), 3), toDateTime64('1970-01-01 00:00:00.000', 3)) AS stored,
    parseDateTime64BestEffort(JSON_VALUE(statement, '$.timestamp'), 3) != toDateTime64('1970-01-01 00:00:00.000', 3) AS is_parsed
FROM saikyo_new.statements