# Generated by Django 4.2.17 on 2025-05-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(help_text='Moodle course ID', unique=True)),
                ('course_name', models.CharField(help_text='Course full name from Moodle', max_length=255)),
                ('parent_category_id', models.IntegerField(help_text='Parent category ID from Moodle')),
                ('parent_category_name', models.CharField(help_text='Parent category name', max_length=255)),
                ('child_category_id', models.IntegerField(help_text='Child category ID from Moodle')),
                ('child_category_name', models.CharField(help_text='Child category name', max_length=255)),
                ('course_sortorder', models.IntegerField(default=0, help_text='Sort order in Moodle')),
                ('course_visible', models.BooleanField(default=True, help_text='Course visibility in Moodle')),
                ('course_startdate', models.DateTimeField(blank=True, help_text='Course start date', null=True)),
                ('course_enddate', models.DateTimeField(blank=True, help_text='Course end date', null=True)),
                ('course_created', models.DateTimeField(help_text='Course creation timestamp')),
                ('subject_category', models.CharField(blank=True, choices=[('english', 'English'), ('mathematics', 'Mathematics')], help_text='Subject category classification', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Last synchronization with Moodle')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course_course',
                'ordering': ['parent_category_name', 'child_category_name', 'course_sortorder'],
                'indexes': [models.Index(fields=['course_id'], name='course_cour_course__88517d_idx'), models.Index(fields=['parent_category_id'], name='course_cour_parent__f19f6b_idx'), models.Index(fields=['child_category_id'], name='course_cour_child_c_6b8ea7_idx'), models.Index(fields=['subject_category'], name='course_cour_subject_85db44_idx'), models.Index(fields=['course_visible'], name='course_cour_course__320e93_idx')],
            },
        ),
    ]
