# Generated by Django 4.2.17 on 2025-06-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level_category',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('junior', 'Junior')], help_text='Level category classification', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level_category'], name='course_cour_level_c_816259_idx'),
        ),
    ]
