"""
Django settings for leaf_school project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from typing import Dict, Any
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment settings
ENVIRONMENT = os.getenv('DJANGO_ENVIRONMENT', 'development')
IS_PRODUCTION = ENVIRONMENT == 'production'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-g$m4*j)xs_v8*e8u6^0ia^if05+l_-w3@p(zdaz2e*a$68z^d_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PRODUCTION
DEBUG = True

# Proxy settings
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
FORCE_SCRIPT_NAME = '/dashboard'

# Accept comma in host headers (fix for proxy configuration)
ALLOWED_HOST_PATTERNS = [
    r'sk\.let\.media\.kyoto-u\.ac\.jp(,\s*sk\.let\.media\.kyoto-u\.ac\.jp)*',
    r'10\.236\.173\.223',
    r'localhost',
]

ALLOWED_HOSTS = ['*'] if DEBUG else [
    'sk.let.media.kyoto-u.ac.jp',
    '10.236.173.223',
    'localhost',
] + ALLOWED_HOST_PATTERNS

CSRF_TRUSTED_ORIGINS = ['https://sk.let.media.kyoto-u.ac.jp']

INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
    '172.17.0.1',
    'school_dashboard',
] if not IS_PRODUCTION else []

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'channels',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_tailwind',
    'core',
    'clickhouse_backend',
    'teacher_student',
]

if not IS_PRODUCTION:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not IS_PRODUCTION:
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'leaf_school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'leaf_school.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'school_db'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    },
    'moodle_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MOODLE_DB_NAME', 'moodle'),
        'USER': os.getenv('MOODLE_DB_USER', 'moodle'),
        'PASSWORD': os.getenv('MOODLE_DB_PASSWORD', 'moodle'),
        'HOST': '127.0.0.1',  # Use IP instead of localhost
        'PORT': os.getenv('MOODLE_DB_PORT', '30102'),
        'OPTIONS': {
            'init_command': "SET SESSION TRANSACTION READ ONLY",
            'charset': 'utf8mb4',
            'use_unicode': True,
            'connect_timeout': 10,
        },
    },
    'bookroll_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('BOOKROLL_DB_NAME', 'bookroll'),
        'USER': os.getenv('BOOKROLL_DB_USER', 'bookroll'),
        'PASSWORD': os.getenv('BOOKROLL_DB_PASSWORD'),
        'HOST': '127.0.0.1',  # Use IP instead of localhost
        'PORT': os.getenv('BOOKROLL_DB_PORT', '30100'),
        'OPTIONS': {
            'init_command': "SET SESSION TRANSACTION READ ONLY",
            'charset': 'utf8mb4',
            'use_unicode': True,
            'connect_timeout': 10,
        },
    },
    'clickhouse_db': {
        'ENGINE': 'clickhouse_backend.backend',
        'NAME': os.getenv('CLICKHOUSE_DB_NAME'),
        'USER': os.getenv('CLICKHOUSE_DB_USER', 'default'),
        'PASSWORD': os.getenv('CLICKHOUSE_DB_PASSWORD'),
        'HOST': os.getenv('CLICKHOUSE_DB_HOST'),
        'PORT': os.getenv('CLICKHOUSE_DB_PORT', '9001'),
        'OPTIONS': {
            'settings': {
                'allow_experimental_window_functions': 1,
            }
        }
    },
}
DATABASE_ROUTERS = ['leaf_school.db_router.DatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Available languages
LANGUAGES = [
    ('en', 'English'),
    ('ja', 'Japanese'),
]

# Location of translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Default language
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_PATH = '/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/dashboard/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise Configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False
WHITENOISE_ALLOW_ALL_ORIGINS = True

# Media files configuration
MEDIA_URL = '/dashboard/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGIN_REDIRECT_URL = 'index'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} [{name}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if not IS_PRODUCTION else ['file'],
            'level': 'INFO',
        },
        'django.channels.server': {
            'handlers': ['console'] if not IS_PRODUCTION else ['file'],
            'level': 'DEBUG' if not IS_PRODUCTION else 'INFO',
        },
        # Add custom logger for authentication events
        'core.views': {
            'handlers': ['console', 'file'] if not IS_PRODUCTION else ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}


# Debug Toolbar settings (development only)
if not IS_PRODUCTION:
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
    ]

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: True,
    }

MEMCACHED_HOST = '127.0.0.1'
MEMCACHED_PORT = '11211'

# Cache configuration
if IS_PRODUCTION:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': f"{os.getenv('MEMCACHED_HOST', 'memcached')}:{os.getenv('MEMCACHED_PORT', '11211')}",
            'OPTIONS': {
                'no_delay': True,
                'ignore_exc': True,
                'max_pool_size': 4,
                'use_pooling': True,
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': f"{MEMCACHED_HOST}:{MEMCACHED_PORT}",
            'OPTIONS': {
                'no_delay': True,
                'ignore_exc': True,
                'max_pool_size': 4,
                'use_pooling': True,
            }
        }
    }

ASGI_APPLICATION = "leaf_school.asgi.application"


# LEAF API SETTINGS
# LEAF API Configuration
LEAF_API_CONFIG: Dict[str, Any] = {
    'HOST': os.getenv('LEAF_API_HOST', '10.236.173.177'),
    'PORT': os.getenv('LEAF_API_PORT', '8090'),
    'CLIENT_ID': os.getenv('LEAF_API_CLIENT_ID', 'client1'),
    'CLIENT_SECRET': os.getenv('LEAF_API_CLIENT_SECRET', 'secret11'),
    'TIMEOUT': int(os.getenv('LEAF_API_TIMEOUT', '30')),
    'MAX_CONNECTIONS': int(os.getenv('LEAF_API_MAX_CONNECTIONS', '10')),
    'MAX_KEEPALIVE_CONNECTIONS': int(os.getenv('LEAF_API_MAX_KEEPALIVE_CONNECTIONS', '5')),
    'CACHE_TTL': int(os.getenv('LEAF_API_CACHE_TTL', '3600')),  # 1 hour default
    'TOKEN_CACHE_KEY': 'leaf_api_token',
    'CONTENT_CACHE_PREFIX': 'leaf_content',
}

# TIME_ZONE = 'Asia/Tokyo'
USE_TZ = True