# Generated by Django 4.2.17 on 2025-05-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date of the holiday', unique=True, verbose_name='Holiday Date')),
                ('name', models.CharField(help_text='The name of the holiday in Japanese', max_length=100, verbose_name='Holiday Name')),
                ('name_en', models.CharField(blank=True, help_text='The name of the holiday in English', max_length=100, null=True, verbose_name='Holiday Name (English)')),
                ('year', models.PositiveIntegerField(db_index=True, help_text='The year this holiday occurs', verbose_name='Year')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Japanese Holiday',
                'verbose_name_plural': 'Japanese Holidays',
                'db_table': 'japanese_holidays',
                'db_table_comment': 'Japanese national holidays data',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['year'], name='holiday_year_idx'), models.Index(fields=['date'], name='holiday_date_idx')],
            },
        ),
    ]
