# Generated by Django 4.2.17 on 2025-06-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Teacher's full name for reference", max_length=255)),
                ('lms_id', models.IntegerField(help_text="Teacher's LMS user ID from Moodle", unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, help_text="Reason for exclusion (e.g., 'Testing account')", max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this exclusion is currently active')),
            ],
            options={
                'verbose_name': 'Teacher Exclusion',
                'verbose_name_plural': 'Teacher Exclusions',
                'db_table': 'teacher_exclusions',
                'ordering': ['name'],
            },
        ),
    ]
